steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/v2-mjv', '--build-arg', 'NEXT_PUBLIC_ENV=production', '.']
    id: 'Build Docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/v2-mjv']
    id: 'Push Docker image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'v2-mjv',
      '--image', 'gcr.io/$PROJECT_ID/v2-mjv',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'NEXT_PUBLIC_ENV=production'
    ]
    id: 'Deploy to Cloud Run Production'

options:
  logging: CLOUD_LOGGING_ONLY
